{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "47dcab65",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import sys\n",
    "import re\n",
    "import math\n",
    "import os\n",
    "import glob\n",
    "from statistics import mean, stdev\n",
    "\n",
    "# import matplotlib\n",
    "# matplotlib.use('module://ipympl.backend_nbagg')\n",
    "# %matplotlib widget\n",
    "\n",
    "# import PyQt5\n",
    "# import os\n",
    "# os.environ[\"QT_API\"] = \"pyqt5\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b0eb3bee",
   "metadata": {},
   "outputs": [],
   "source": [
    "sys.path.append(\"/Users/pnr5sh/Documents/phd/mmmp/\")\n",
    "import sidchaini.sidhelpers as sidhelpers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9f5c33fd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['wise_objid', 'IAU name', 'Internal name/s', 'Obj. RA', 'Obj. DEC',\n",
       "       'Obj. Type', 'Redshift', 'Spec. ID', 'Obs-date', 'JD', 'Phase (days)',\n",
       "       'From', 'Telescope', 'Instrument', 'Observer/s', 'Reducer/s',\n",
       "       'Source group', 'Public', 'Associated groups', 'End prop. period',\n",
       "       'Ascii file', 'Fits file', 'Spec. type', 'Spec. quality',\n",
       "       'Extinction-Corrected', 'WL Medium', 'WL Units',\n",
       "       'Flux Unit Coefficient', 'Spec. units', 'Flux Calibrated By',\n",
       "       'Exp-time', 'Aperture (slit)', 'HA', 'Airmass', 'Dichroic', 'Grism',\n",
       "       'Grating', 'Blaze', 'Lambda-min', 'Lambda-max', 'Del-Lambda', 'Contrib',\n",
       "       'Publish', 'Remarks', 'Created by', 'Creation date'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#reading in meta data from sid's dir\n",
    "header = ['Obj. ID', 'IAU name', 'Internal name/s', 'Obj. RA', 'Obj. DEC', 'Obj. Type',\n",
    "          'Redshift', 'Spec. ID', 'Obs-date', 'JD', 'Phase (days)', 'From', 'Telescope',\n",
    "          'Instrument', 'Observer/s', 'Reducer/s', 'Source group', 'Public', 'Associated groups',\n",
    "          'End prop. period', 'Ascii file', 'Fits file', 'Spec. type', 'Spec. quality',\n",
    "          'Extinction-Corrected', 'WL Medium','WL Units', 'Flux Unit Coefficient', 'Spec. units',\n",
    "          'Flux Calibrated By', 'Exp-time', 'Aperture (slit)', 'HA', 'Airmass', 'Dichroic', 'Grism',\n",
    "          'Grating', 'Blaze', 'Lambda-min', 'Lambda-max', 'Del-Lambda', 'Contrib', 'Publish', 'Remarks',\n",
    "          'Created by', 'Creation date']\n",
    "all_spec_meta = pd.read_csv('../sidchaini/1. download ALL wise data/wiserep_spectra_combined.csv', header='infer')\n",
    "all_spec_meta.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "761cc671",
   "metadata": {},
   "outputs": [],
   "source": [
    "# filters for specific types\n",
    "multi_types = (all_spec_meta['Obj. Type']=='SN IIb')|(all_spec_meta['Obj. Type']=='SN Ib')|(all_spec_meta['Obj. Type']=='SN Ic')|(all_spec_meta['Obj. Type']=='SLSN-I')|(all_spec_meta['Obj. Type']=='SLSN-II')|(all_spec_meta['Obj. Type']=='SN IIn')\n",
    "\n",
    "#filters for ZTF/P60 data\n",
    "p60 = (all_spec_meta['Telescope']=='P60')\n",
    "sedm = (all_spec_meta['Instrument']=='SEDM')\n",
    "\n",
    "#creating filters based on types for big DF\n",
    "iib = (all_spec_meta['Obj. Type']=='SN IIb')\n",
    "ib = (all_spec_meta['Obj. Type']=='SN Ib')\n",
    "ic = (all_spec_meta['Obj. Type']=='SN Ic')\n",
    "slsni = (all_spec_meta['Obj. Type']=='SLSN-I')\n",
    "slsnii = (all_spec_meta['Obj. Type']=='SLSN-II')\n",
    "iin = (all_spec_meta['Obj. Type']=='SN IIn')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "dfffb93c",
   "metadata": {},
   "outputs": [],
   "source": [
    "#creates ztf_info*.csv files for submitting batch queries to ZTF FP server\n",
    "\n",
    "types_str = ['SN IIb', 'SN Ib', 'SN Ic', 'SLSN-I', 'SLSN-II', 'SN IIn']\n",
    "types_flags = [iib, ib, ic, slsni, slsnii, iin]\n",
    "\n",
    "for i,types in enumerate(types_flags):\n",
    "    objs = all_spec_meta.loc[types&p60&sedm,'IAU name'].unique().tolist() #list of IIb names\n",
    "\n",
    "    ras, decs, jd_starts, jd_ends, obj_name = [],[],[],[],[]\n",
    "    for j in range(len(objs)):\n",
    "        ra = all_spec_meta.loc[types&p60&sedm&(all_spec_meta['IAU name']==objs[j]), 'Obj. RA'].iloc[0]\n",
    "        dec = all_spec_meta.loc[types&p60&sedm&(all_spec_meta['IAU name']==objs[j]), 'Obj. DEC'].iloc[0]\n",
    "        jd = all_spec_meta.loc[types&p60&sedm&(all_spec_meta['IAU name']==objs[j]), 'JD'].iloc[0] #JD of spectra taken for individ obj\n",
    "        name = all_spec_meta.loc[types&p60&sedm&(all_spec_meta['IAU name']==objs[j]), 'IAU name'].iloc[0]\n",
    "        ras.append(ra)\n",
    "        decs.append(dec)\n",
    "        jd_starts.append(jd-50)\n",
    "        jd_ends.append(jd+150)\n",
    "        obj_name.append(name)\n",
    "    \n",
    "    typs = [types_str[i]]*len(ras)\n",
    "    d = {'ra':ras, 'dec':decs, 'jd_start':jd_starts, 'jd_end':jd_ends, 'obj_name':obj_name, 'type':typs}\n",
    "    ztf_info = pd.DataFrame(d)\n",
    "    ztf_info.to_csv(f\"./ztf_fp_info_for_{types_str[i]}.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "38bc505b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# creating df of only objects meeting our target types, from ZTF \n",
    "mp_spec_df = all_spec_meta.loc[multi_types&p60&sedm]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a31d5027",
   "metadata": {},
   "outputs": [],
   "source": [
    "# types_str = ['SN IIb', 'SN Ib', 'SN Ic', 'SLSN-I']\n",
    "# types_flags = [iib, ib, ic, slsni]\n",
    "\n",
    "# for i,types in enumerate(types_flags):\n",
    "#     objs = all_spec_meta.loc[types&p60&sedm,'IAU name'].unique().tolist() #list of IIb names\n",
    "\n",
    "#     ras, decs, jd_starts, jd_ends, obj_name = [],[],[],[],[]\n",
    "#     for j in range(len(objs)):\n",
    "#         ra = all_spec_meta.loc[types&p60&sedm&(all_spec_meta['IAU name']==objs[j]), 'Obj. RA'].iloc[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "b97f880e",
   "metadata": {},
   "outputs": [],
   "source": [
    "#read in ztf lc data into DF and also header info\n",
    "#isolate ra/dec from header and cross-match to mp_spec_df values to find corresponding SN\n",
    "#rename file \n",
    "\n",
    "def rename_via_coords(datadir,df2match):\n",
    "    filenames = [datadir+f for f in os.listdir(datadir)]\n",
    "\n",
    "    ra_str = '# Requested input R.A. = '\n",
    "    dec_str = '# Requested input Dec. = '\n",
    "    for i,filename in enumerate(filenames):\n",
    "        ra = float()\n",
    "        dec = float()\n",
    "        with open(filename, 'r') as file:\n",
    "            header = [next(file) for x in range(54)]\n",
    "            for line in header:\n",
    "                if line.startswith(ra_str):\n",
    "                    ra = float(line[len(ra_str):-8])\n",
    "                if line.startswith(dec_str):\n",
    "                    dec = float(line[len(dec_str):-8])\n",
    "        idx = [df2match['Obj. RA'].sub(ra).abs().idxmin()] # list of index matching the ra\n",
    "        if len(idx)>0:\n",
    "            name = df2match.loc[idx[0],'IAU name'][3:]\n",
    "            savefile = datadir+name+'_fp_lc.txt'\n",
    "            #rename the file w/ the IAU name\n",
    "            os.system(f\"cp {filename} {savefile}\")\n",
    "        else:\n",
    "            print(f\"Unable to find closest match to RA={ra}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1726c052",
   "metadata": {},
   "outputs": [],
   "source": [
    "#only run if files haven't been renamed \n",
    "#if running on already renamed files, os will recognize they are identical and skip\n",
    "\n",
    "rename_via_coords('./ztf_fp_data/ib/',mp_spec_df)\n",
    "rename_via_coords('./ztf_fp_data/ic/',mp_spec_df)\n",
    "rename_via_coords('./ztf_fp_data/iib/',mp_spec_df)\n",
    "rename_via_coords('./ztf_fp_data/iin/',mp_spec_df)\n",
    "rename_via_coords('./ztf_fp_data/slsni/',mp_spec_df)\n",
    "rename_via_coords('./ztf_fp_data/slsnii/',mp_spec_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "id": "bf1df365",
   "metadata": {},
   "outputs": [],
   "source": [
    "# #check if the matched file names match the object names\n",
    "\n",
    "# li = mp_spec_df.loc[mp_spec_df['Obj. Type']=='SN Ib', 'IAU name'].sort_values().unique()\n",
    "# for l in li:\n",
    "#     print(l)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "03bf3734",
   "metadata": {},
   "outputs": [],
   "source": [
    "# dropping bad obs\n",
    "# centering LCs around date of first spectra (-50, +150 days)\n",
    "# creating mag and mag_err cols\n",
    "# dropping points w/ e_mag>2 mags\n",
    "# creating mjd col\n",
    "\n",
    "def create_ztf_lc_dfs(datadir, sn_type, check_names=False):\n",
    "        files = sorted(glob.glob(datadir+'*_fp_lc.txt'))\n",
    "        ztf_info_df = pd.read_csv(f'ztf_fp_info_for_{sn_type}.csv')\n",
    "\n",
    "        if (sn_type == 'SN IIb') or (sn_type =='SN IIn'):\n",
    "                startindx = 18\n",
    "        elif (sn_type == 'SN Ic') or (sn_type =='SN Ib'):\n",
    "                startindx = 17\n",
    "        elif sn_type == 'SLSN-I':\n",
    "                startindx = 20\n",
    "        elif sn_type == 'SLSN-II':\n",
    "                startindx = 21\n",
    "        else:\n",
    "                print(f'SN type {sn_type} unsupported or not in format SN XX / SLSN-XX')\n",
    "                return\n",
    "\n",
    "        sn_names, lc_dfs = [],[]\n",
    "        for file in files:\n",
    "                sn_name = file[startindx:-10] #NOTE: FIRST INDEX CHANGES W/ DATADIR NAME LENGTH\n",
    "                if check_names:\n",
    "                        print(sn_name)\n",
    "                        continue\n",
    "                \n",
    "                sn_names.append(sn_name)\n",
    "\n",
    "                cols = ['index', 'field', 'ccdid', 'qid', 'filter', 'pid', 'infobitssci', 'sciinpseeing', 'scibckgnd', 'scisigpix',\n",
    "                        'zpmaginpsci', 'zpmaginpsciunc', 'zpmaginpscirms', 'clrcoeff', 'clrcoeffunc', 'ncalmatches', 'exptime',\n",
    "                        'adpctdif1', 'adpctdif2', 'diffmaglim', 'zpdiff', 'programid', 'jd', 'rfid', 'forcediffimflux', 'forcediffimfluxunc',\n",
    "                        'forcediffimsnr', 'forcediffimchisq', 'forcediffimfluxap', 'forcediffimfluxuncap', 'forcediffimsnrap', 'aperturecorr',\n",
    "                        'dnearestrefsrc', 'nearestrefmag', 'nearestrefmagunc', 'nearestrefchi', 'nearestrefsharp', 'refjdstart', 'refjdend', 'procstatus']\n",
    "                df = pd.read_csv(file, names=cols, header=None, sep=\" \", skiprows=54)\n",
    "                df = df.set_index(df['index'])  # manually setting indeces\n",
    "                df = df.drop(columns=['index']) # drop duplicated index \n",
    "                df = df[(df['infobitssci'] < 33554432) & (df['scisigpix'] <= 25) & (df['sciinpseeing'] <= 4) & (df['forcediffimflux']!=-99999.0)].reset_index(drop=True) #clean according to docs\n",
    "\n",
    "                # cut df down to -50 days to +365 days centered on date of first spectra\n",
    "                # time window included in ztf_fp_info*csv files for each obj type\n",
    "                obj = ztf_info_df.loc[ztf_info_df['obj_name'].str[3:]==sn_name]\n",
    "                start_jd = obj['jd_start'].iloc[0]\n",
    "                end_jd = obj['jd_end'].iloc[0]\n",
    "                df_cut = df.loc[(df['jd']<end_jd)&(df['jd']>start_jd)] #only selecting points that fall within specified time window\n",
    "                df_cut = df_cut.reset_index(drop=True)\n",
    "                df_cut = df_cut.infer_objects() #infering dtype of columns\n",
    "\n",
    "                mag = df_cut['zpdiff'] - 2.5 * np.log10(df_cut['forcediffimflux'])\n",
    "                sigma_mag = 1.0857 * df_cut['forcediffimfluxunc']/df_cut['forcediffimflux']\n",
    "                df_cut['mag'] = mag\n",
    "                df_cut['e_mag'] = sigma_mag\n",
    "                df_cut = df_cut.loc[(df_cut['forcediffimflux']>0) & (df_cut['e_mag']<2)].reset_index(drop=True) #only selecting points w/ non-nan mags and errorbars less than 2 mags\n",
    "                df_cut['mjd'] = df_cut['jd']-2400000.5\n",
    "\n",
    "                lc_dfs.append(df_cut)\n",
    "\n",
    "        return sn_names, lc_dfs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "b44402f5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n",
      "/Users/pnr5sh/miniconda3/envs/astro/lib/python3.11/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10\n",
      "  result = getattr(ufunc, method)(*inputs, **kwargs)\n"
     ]
    }
   ],
   "source": [
    "sn_names_ib, lc_dfs_ib = create_ztf_lc_dfs('./ztf_fp_data/ib/','SN Ib')\n",
    "sn_names_ic, lc_dfs_ic = create_ztf_lc_dfs('./ztf_fp_data/ic/','SN Ic')\n",
    "sn_names_iib, lc_dfs_iib = create_ztf_lc_dfs('./ztf_fp_data/iib/','SN IIb')\n",
    "sn_names_iin, lc_dfs_iin = create_ztf_lc_dfs('./ztf_fp_data/iin/','SN IIn')\n",
    "sn_names_slsni, lc_dfs_slsni = create_ztf_lc_dfs('./ztf_fp_data/slsni/','SLSN-I')\n",
    "sn_names_slsnii, lc_dfs_slsnii = create_ztf_lc_dfs('./ztf_fp_data/slsnii/','SLSN-II')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "16f63ca9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# plotting to see if data exists around SN + data spread across filters + multi-peakedness\n",
    "def plot_all_ztf_lcs(lc_dfs,sn_names,interactive=False,save=False,datadir='./figures/ztf_lcs/'):\n",
    "    if not interactive:\n",
    "        %matplotlib inline\n",
    "    else:\n",
    "        %matplotlib widget\n",
    "\n",
    "    for i in range(len(lc_dfs)):\n",
    "        gband = (lc_dfs[i]['filter']=='ZTF_g')\n",
    "        rband = (lc_dfs[i]['filter']=='ZTF_r')\n",
    "        iband = (lc_dfs[i]['filter']=='ZTF_i')\n",
    "\n",
    "        plt.figure(figsize=(8,6))\n",
    "        plt.errorbar(lc_dfs[i].loc[gband, 'mjd'], lc_dfs[i].loc[gband, 'mag'], yerr=lc_dfs[i].loc[gband, 'e_mag'],ls='', marker='.', color='darkseagreen')\n",
    "        plt.errorbar(lc_dfs[i].loc[rband, 'mjd'], lc_dfs[i].loc[rband, 'mag'], yerr=lc_dfs[i].loc[rband, 'e_mag'],ls='', marker='.', color='palevioletred')\n",
    "        plt.errorbar(lc_dfs[i].loc[iband, 'mjd'], lc_dfs[i].loc[iband, 'mag'], yerr=lc_dfs[i].loc[iband, 'e_mag'],ls='', marker='.', color='goldenrod')\n",
    "        plt.gca().invert_yaxis()\n",
    "        plt.title(sn_names[i])\n",
    "        plt.xlabel('MJD', fontsize=15)\n",
    "        plt.ylabel('Apparent Mag', fontsize=15)\n",
    "        if save:\n",
    "            plt.savefig(f'{datadir}{sn_names[i]}_ztf_lc.png', bbox_inches='tight', dpi=300)\n",
    "        plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "id": "7ccc117e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# plot_all_ztf_lcs(lc_dfs_ib,sn_names_ib,save=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "f944b2fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "# plot_all_ztf_lcs(lc_dfs_ic,sn_names_ic,save=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "e6b2d1ce",
   "metadata": {},
   "outputs": [],
   "source": [
    "# plot_all_ztf_lcs(lc_dfs_iib,sn_names_iib,save=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "8a5eb8c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# plot_all_ztf_lcs(lc_dfs_iin,sn_names_iin,save=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "9d393bd7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# plot_all_ztf_lcs(lc_dfs_slsni,sn_names_slsni,save=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "c8c43e29",
   "metadata": {},
   "outputs": [],
   "source": [
    "# plot_all_ztf_lcs(lc_dfs_slsnii,sn_names_slsnii,save=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "8a7bd2d8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# date of max fitting for LCs\n",
    "\n",
    "# craig's function from adap\n",
    "\n",
    "def plot_fit_for_max(\n",
    "    sn_name, # was sn_class\n",
    "    mjd_array,\n",
    "    mag_array,\n",
    "    err_array,\n",
    "    fit_mjds,\n",
    "    fit_mags,\n",
    "    fit_errs,\n",
    "    inds_to_fit,\n",
    "    ):\n",
    "    \"\"\"\n",
    "    Takes as input arrays for MJD, mag, and err for a filter\n",
    "    as well as the guess for the MJD of maximum and an array\n",
    "    to shift the lightcurve over,\n",
    "    and returns estimates of the peak MJD and mag at peak\n",
    "    \"\"\"\n",
    "\n",
    "    fig, ax = plt.subplots()\n",
    "\n",
    "    ax.errorbar(mjd_array, mag_array, yerr=err_array, fmt=\"o\", color=\"gray\", ms=1)\n",
    "    ax.errorbar(\n",
    "        fit_mjds,\n",
    "        fit_mags,\n",
    "        yerr=fit_errs,\n",
    "        fmt=\"o\",\n",
    "        color=\"blue\",\n",
    "        label=\"Used in Fitting\",\n",
    "        ms=3,\n",
    "    )\n",
    "    if len(mjd_array[inds_to_fit]) > 0:\n",
    "        plt.ylim(min(mag_array[inds_to_fit]) - 0.5, max(mag_array[inds_to_fit]) + 0.5)\n",
    "    plt.xlabel(\"MJD\")\n",
    "    plt.ylabel(\"Apparent Magnitude\")\n",
    "    plt.title(sn_name)\n",
    "    plt.legend()\n",
    "    plt.gca().invert_yaxis()\n",
    "\n",
    "    # plt.show()\n",
    "\n",
    "def fit_for_max(df, sn_name, filt, shift_array=[-3, -2, -1, 0, 1, 2, 3], plot=False, offset=0, window=10):\n",
    "    \"\"\"\n",
    "    Takes as input arrays for MJD, mag, and err for a filter\n",
    "    as well as the guess for the MJD of maximum and an array\n",
    "    to shift the lightcurve over,\n",
    "    and returns estimates of the peak MJD and mag at peak\n",
    "    \"\"\"\n",
    "    # mjd_array = np.asarray([phot[\"mjd\"] for phot in self.data[filt] if not phot.get(\"nondetection\", False)])\n",
    "    # mag_array = np.asarray([phot[\"mag\"] for phot in self.data[filt] if not phot.get(\"nondetection\", False)])\n",
    "    # err_array = np.asarray([phot[\"err\"] for phot in self.data[filt] if not phot.get(\"nondetection\", False)])\n",
    "\n",
    "    mjd_array = df.loc[df['filter']==filt, 'mjd'].to_numpy()\n",
    "    mag_array = df.loc[df['filter']==filt, 'mag'].to_numpy()\n",
    "    err_array = df.loc[df['filter']==filt, 'e_mag'].to_numpy()\n",
    "\n",
    "    if len(mag_array) < 4:  # == 0:\n",
    "        print('len(mag)<4')\n",
    "        return None, None\n",
    "\n",
    "    initial_guess_mjd_max = mjd_array[np.where((mag_array == min(mag_array)))[0]][0] + offset\n",
    "\n",
    "    fit_inds = np.where((abs(mjd_array - initial_guess_mjd_max) < 40))[0] #was 30\n",
    "    if len(fit_inds) < 4:\n",
    "        print('not enough points +/-30 days from initial guess')\n",
    "        return None, None\n",
    "\n",
    "    fit_coeffs = np.polyfit(mjd_array[fit_inds], mag_array[fit_inds], 3)\n",
    "    guess_phases = np.arange(min(mjd_array[fit_inds]), max(mjd_array[fit_inds]), 1)\n",
    "    p = np.poly1d(fit_coeffs)\n",
    "    guess_best_fit = p(guess_phases)\n",
    "\n",
    "    if len(guess_best_fit) == 0:\n",
    "        print('len(best_guess)=0')\n",
    "        return None, None\n",
    "\n",
    "    guess_mjd_max = guess_phases[np.where((guess_best_fit == min(guess_best_fit)))[0]][0]\n",
    "\n",
    "    # print(f'GUESS MJD MAX = {guess_mjd_max}')\n",
    "    ### Do this because the array might not be ordered\n",
    "    inds_to_fit = np.where((mjd_array > guess_mjd_max - window) & (mjd_array < guess_mjd_max + window))\n",
    "    # print(f'INDS_TO_FIt = {inds_to_fit}')\n",
    "    \n",
    "    if len(inds_to_fit[0]) < 4:\n",
    "        print('Select a wider date range')\n",
    "        return None, None\n",
    "\n",
    "    numdata = len(mjd_array[inds_to_fit])\n",
    "    numiter = max(int(numdata * np.log(numdata) ** 2), 200)\n",
    "\n",
    "    fit_mjds = mjd_array[inds_to_fit]\n",
    "    fit_mags = mag_array[inds_to_fit]\n",
    "    fit_errs = err_array[inds_to_fit]\n",
    "\n",
    "    if plot:\n",
    "        plot_fit_for_max(\n",
    "            sn_name=sn_name,\n",
    "            mjd_array=mjd_array,\n",
    "            mag_array=mag_array,\n",
    "            err_array=err_array,\n",
    "            fit_mjds=fit_mjds,\n",
    "            fit_mags=fit_mags,\n",
    "            fit_errs=fit_errs,\n",
    "            inds_to_fit=inds_to_fit,\n",
    "        )\n",
    "\n",
    "    peak_mags = []\n",
    "    peak_mjds = []\n",
    "    for num in range(numiter):\n",
    "        simulated_points = []\n",
    "\n",
    "        ### Shift by a certain number of days to randomly sample the light curve\n",
    "        sim_shift = np.random.choice(shift_array)\n",
    "\n",
    "        inds_to_fit = np.where((mjd_array > guess_mjd_max - (window/2) + sim_shift) & (mjd_array < guess_mjd_max + (window/2) + sim_shift))[0]\n",
    "        if len(inds_to_fit) > 0:\n",
    "\n",
    "            fit_mjds = mjd_array[inds_to_fit]\n",
    "            fit_mags = mag_array[inds_to_fit]\n",
    "            fit_errs = err_array[inds_to_fit]\n",
    "\n",
    "            for i in range(len(fit_mjds)):\n",
    "                simulated_points.append(np.random.normal(fit_mags[i], fit_errs[i]))\n",
    "\n",
    "            fit = np.polyfit(fit_mjds, simulated_points, 2)\n",
    "            f = np.poly1d(fit)\n",
    "            fit_time = np.linspace(min(fit_mjds), max(fit_mjds), 100)\n",
    "\n",
    "            if num % 25 == 0 and plot:\n",
    "                plt.plot(fit_time, f(fit_time), color=\"black\", linewidth=0.5)\n",
    "            peak_mag = min(f(fit_time))\n",
    "            peak_mags.append(peak_mag)\n",
    "            peak_mjds.append(fit_time[np.argmin(f(fit_time))])\n",
    "\n",
    "    if len(peak_mjds) == 0:\n",
    "        print('len(peak_mjds)=0')\n",
    "        return None, None\n",
    "\n",
    "    if plot:\n",
    "        plt.errorbar(\n",
    "            mean(peak_mjds),\n",
    "            mean(peak_mags),\n",
    "            xerr=stdev(peak_mjds),\n",
    "            yerr=stdev(peak_mags),\n",
    "            color=\"red\",\n",
    "            fmt=\"o\",\n",
    "            label=\"Best Fit Peak\",\n",
    "        )\n",
    "        plt.xlim(guess_mjd_max - 30, guess_mjd_max + 30)\n",
    "        plt.legend()\n",
    "        plt.show()\n",
    "\n",
    "    return mean(peak_mjds), mean(peak_mags)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "78e086a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# %matplotlib qt\n",
    "\n",
    "def fit_max(\n",
    "        dfs,\n",
    "        sn_names,\n",
    "        savefile,\n",
    "        plot=True,\n",
    "        first_fit=False,\n",
    "        refit_r=False,\n",
    "        refit_g=False,\n",
    "        inds_to_fit=[],\n",
    "        save2file=False,\n",
    "        window=10,\n",
    "        ):\n",
    "          \n",
    "    if first_fit:\n",
    "        #initialize savefile\n",
    "        with open(savefile, 'a') as file:\n",
    "            file.write('#sn_name peak_mjd peak_mag filt\\n')\n",
    "        file.close()\n",
    "\n",
    "        filt = 'ZTF_g'\n",
    "\n",
    "        for i,df in enumerate(dfs):\n",
    "            sn_name = sn_names[i]\n",
    "            print(i, sn_name)\n",
    "\n",
    "            peak_mjd, peak_mag = fit_for_max(df, sn_name, filt,\n",
    "                                             shift_array=[-3, -2, -1, 0, 1, 2, 3],\n",
    "                                             plot=plot, offset=0, window=window)\n",
    "            print(peak_mjd, peak_mag)\n",
    "\n",
    "            if save2file:\n",
    "                line = f'{sn_name} {peak_mjd} {peak_mag} {filt}\\n'\n",
    "                with open(savefile, 'a') as file:\n",
    "                    file.write(line)\n",
    "                file.close()\n",
    "\n",
    "    elif refit_r:\n",
    "        filt = 'ZTF_r'\n",
    "        if not inds_to_fit:\n",
    "            print('Must include indeces to slice on')\n",
    "            return\n",
    "        \n",
    "        for i,df in enumerate(dfs):\n",
    "            if any(i == x for x in inds_to_fit):\n",
    "                sn_name = sn_names[i]\n",
    "                print(i, sn_name)\n",
    "\n",
    "                peak_mjd, peak_mag = fit_for_max(df, sn_name, filt,\n",
    "                                                 shift_array=[-3, -2, -1, 0, 1, 2, 3],\n",
    "                                                 plot=plot, offset=0, window=window)\n",
    "                print(peak_mjd, peak_mag)\n",
    "\n",
    "                if save2file:\n",
    "                    line = f'{sn_name} {peak_mjd} {peak_mag} {filt}\\n'\n",
    "                    with open(savefile, 'a') as file:\n",
    "                        file.write(line)\n",
    "                    file.close()\n",
    "\n",
    "    elif refit_g:\n",
    "        filt = 'ZTF_g'\n",
    "        if not inds_to_fit:\n",
    "            print('Must include indeces to slice on')\n",
    "            return\n",
    "        \n",
    "        for i,df in enumerate(dfs):\n",
    "            if any(i == x for x in inds_to_fit):\n",
    "                sn_name = sn_names[i]\n",
    "                print(i, sn_name)\n",
    "\n",
    "                peak_mjd, peak_mag = fit_for_max(df, sn_name, filt,\n",
    "                                                 shift_array=[-3, -2, -1, 0, 1, 2, 3],\n",
    "                                                 plot=plot, offset=0, window=window)\n",
    "                print(peak_mjd, peak_mag)\n",
    "\n",
    "                if save2file:\n",
    "                    line = f'{sn_name} {peak_mjd} {peak_mag} {filt}\\n'\n",
    "                    with open(savefile, 'a') as file:\n",
    "                        file.write(line)\n",
    "                    file.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bbec5214",
   "metadata": {},
   "outputs": [],
   "source": [
    "#fitting max of LC for Ib\n",
    "\n",
    "savefile = './ztf_fp_data/peak_fit_ib.txt'\n",
    "\n",
    "# refit_g_inds = []\n",
    "# refit_r_inds = []\n",
    "\n",
    "fit_max(lc_dfs_ib, sn_names_ib, savefile, plot=False, first_fit=False,\n",
    "        refit_r=False, refit_g=False, inds_to_fit=[],\n",
    "        save2file=False, window=15) #window = 15 for first fit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ecc58ec4",
   "metadata": {},
   "outputs": [],
   "source": [
    "#fitting max of LC for Ic\n",
    "\n",
    "savefile = './ztf_fp_data/peak_fit_ic.txt'\n",
    "\n",
    "# refit_g_inds = []\n",
    "# refit_r_inds = []\n",
    "\n",
    "fit_max(lc_dfs_ic, sn_names_ic, savefile, plot=False, first_fit=False,\n",
    "        refit_r=False, refit_g=False, inds_to_fit=[],\n",
    "        save2file=False, window=15) #window = 15 for first fit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "875efe1d",
   "metadata": {},
   "outputs": [],
   "source": [
    "#fitting max of LC for IIb\n",
    "\n",
    "savefile = './ztf_fp_data/peak_fit_iib.txt'\n",
    "\n",
    "# refit_g_inds = []\n",
    "# refit_r_inds = []\n",
    "\n",
    "fit_max(lc_dfs_iib, sn_names_iib, savefile, plot=False, first_fit=False,\n",
    "        refit_r=False, refit_g=False, inds_to_fit=[],\n",
    "        save2file=False, window=15) #window = 15 for first fit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f0e62f23",
   "metadata": {},
   "outputs": [],
   "source": [
    "#fitting max of LC for IIn\n",
    "\n",
    "savefile = './ztf_fp_data/peak_fit_iin.txt'\n",
    "\n",
    "# refit_g_inds = []\n",
    "# refit_r_inds = []\n",
    "\n",
    "fit_max(lc_dfs_iin, sn_names_iin, savefile, plot=False, first_fit=False,\n",
    "        refit_r=False, refit_g=False, inds_to_fit=[],\n",
    "        save2file=False, window=15) #window = 15 for first fit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "df85759c",
   "metadata": {},
   "outputs": [],
   "source": [
    "#fitting max of LC for SLSN-I\n",
    "\n",
    "savefile = './ztf_fp_data/peak_fit_slsni.txt'\n",
    "\n",
    "# refit_g_inds = []\n",
    "# refit_r_inds = []\n",
    "\n",
    "fit_max(lc_dfs_slsni, sn_names_slsni, savefile, plot=False, first_fit=False,\n",
    "        refit_r=False, refit_g=False, inds_to_fit=[],\n",
    "        save2file=False, window=15) #window = 15 for first fit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3dd9e1a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#fitting max of LC for SLSN-II\n",
    "\n",
    "savefile = './ztf_fp_data/peak_fit_slsnii.txt'\n",
    "\n",
    "# refit_g_inds = []\n",
    "# refit_r_inds = []\n",
    "\n",
    "fit_max(lc_dfs_slsnii, sn_names_slsnii, savefile, plot=False, first_fit=False,\n",
    "        refit_r=False, refit_g=False, inds_to_fit=[],\n",
    "        save2file=False, window=15) #window = 15 for first fit"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "astro",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
